theme: jekyll-theme-cayman
title: "EasyMariaDB" 
description: >
 Facilita la creación, desde LibreOffice, de bases de datos y usuarios de MariaDB y MySQL
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - prueba.md
  - InstalarMariaDB.md
  - InstalarMySQM.md
