theme: jekyll-theme-time-machine
title: "EasyMariaDB" 
description: >
 Facilita la creación, desde LibreOffice, de bases de datos y usuarios de MariaDB y MySQL
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - ayuda.md
  - InstalarMariaDB.md
  - InstalarMySQL.md
  - clienteservidor.md
  - prueba.md
  - /img/UsuarioEliminado.png
