theme: jekyll-theme-cayman
title: "EasyMariaDB" 
description: >
 Facilita la creación, desde LibreOffice, de bases de datos y usuarios de MariaDB y MySQL
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - prueba.md
