theme: jekyll-theme-cayman
title: "EasyMariaDB" 
description: >
 Facilita la creación de bases de datos y usuarios de MariaDB y MySQL desde LibreOffice 
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - ayuda.md
  - InstalarMariaDB.md
  - InstalarMySQL.md
  - clienteservidor.md
